#!/usr/bin/env python3
"""
Generate Word roadmap documents in docs/.
Requires: pip install python-docx

Usage (from repo root):
  pip install python-docx
  python scripts/build_feature_roadmap_docx.py
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"

# (section title, list of bullet strings)
SECTIONS: list[tuple[str, list[str]]] = [
    (
        "Already in the 1-week plan (see FINSAVVY_WEEK_PLAN_2026)",
        [
            "Monthly budgets per category with dashboard comparison",
            "CSV export of transactions from the UI",
            "Month-over-month comparison on dashboard",
            "Receipt ↔ bank transaction linking",
            "Settings / categories overview page",
            "Polish, README, changelog pass",
        ],
    ),
    (
        "Core product gaps (no external bank API)",
        [
            "Payslip PDF parsing → auto-fill taxable income (manual entry today)",
            "Recurring / subscription detection and tagging",
            "Savings goals and “pots”",
            "Transaction search across all history (dashboard search is per-period)",
            "Split transactions / multiple categories per line",
            "Editable rules UI (“if description contains X → category Y”)",
            "“All accounts” aggregated dashboard view",
            "Tags and custom labels beyond category/party",
            "Bill reminders and due dates",
            "Household / shared expenses and multi-user accounts",
            "Investment holdings and net worth",
        ],
    ),
    (
        "Security and compliance",
        [
            "Two-factor authentication (2FA)",
            "Session / device management",
            "Full data export (GDPR-style package)",
            "Structured audit log",
        ],
    ),
    (
        "Infrastructure and quality",
        [
            "Alembic (or equivalent) DB migrations instead of ad-hoc ALTER",
            "Automated tests (API + critical UI flows)",
            "Structured logging and metrics",
        ],
    ),
    (
        "Requires external API, integration, or automation (out of scope for this pass)",
        [
            "Live bank feeds (Open Banking)",
            "Real credit bureau score and history (CREDIT_API_KEY + provider SDK)",
            "Email / push notifications",
            "Scheduled cron jobs (use GET /api/alerts manually or self-hosted cron)",
        ],
    ),
    (
        "Client experience",
        [
            "Progressive Web App (PWA) or native mobile app",
            "Stronger mobile-responsive layouts",
        ],
    ),
]

# Subset implemented in codebase (for STATUS document)
DONE_LABELS: set[str] = {
    "Monthly budgets per category with dashboard comparison",
    "CSV export of transactions from the UI",
    "Month-over-month comparison on dashboard",
    "Receipt ↔ bank transaction linking",
    "Settings / categories overview page",
}


def _build_docx(path: Path, *, mark_done: bool) -> None:
    try:
        from docx import Document
        from docx.shared import Pt
    except ImportError:
        print("Install python-docx: pip install python-docx", file=sys.stderr)
        sys.exit(1)

    doc = Document()
    title = (
        "Fin Savvy – Feature roadmap (full list)"
        if not mark_done
        else "Fin Savvy – Feature roadmap (with implementation status)"
    )
    p = doc.add_heading(title, 0)
    p.runs[0].font.size = Pt(18)

    doc.add_paragraph(
        "Generated by scripts/build_feature_roadmap_docx.py. "
        "Items marked [DONE] in the status document were implemented without external APIs; "
        "cron and bureau APIs are still manual / placeholder."
    )

    for section, bullets in SECTIONS:
        doc.add_heading(section, level=1)
        for b in bullets:
            prefix = "[DONE] " if mark_done and b in DONE_LABELS else ""
            doc.add_paragraph(prefix + b, style="List Bullet")

    doc.add_heading("Notes", level=1)
    doc.add_paragraph(
        "See docs/CORE_FEATURES.md for how existing features map to the codebase. "
        "Existing: PDF/CSV import, classification (rules + optional ML), receipts with optional OCR, "
        "cash vs receipts, tax estimate + text report, Pandas budget API, in-app alerts, credit placeholder API."
    )

    path.parent.mkdir(parents=True, exist_ok=True)
    doc.save(str(path))
    print("Wrote", path)


def main() -> None:
    _build_docx(DOCS / "FINSAVVY_FEATURE_ROADMAP_FULL.docx", mark_done=False)
    _build_docx(DOCS / "FINSAVVY_FEATURE_ROADMAP_STATUS.docx", mark_done=True)


if __name__ == "__main__":
    main()
